#!/usr/bin/env bash

if [ -z "$1" ]; then
	echo "error"
fi

mkdir ./lib/day$1
touch ./lib/day$1/input
cat << EOF  > ./lib/day$1/day$1.ex
defmodule Day$1 do
	@doc """
	## Examples
		iex> Input.read($1) |> Day$1.part1
		:result
	"""
	def part1(input) do
		input
	end

	@doc """
	## Examples
		iex> Input.read($1) |> Day$1.part2
		:result
	"""
	def part2(input) do
		(input)
	end
end
EOF

sed -i "s|end|  doctest Day$1\nend|" ./test/advent_of_code2020_test.exs